package dao.entities;
// Generated 23 sept. 2017 09:52:10 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Medecin generated by hbm2java
 */
@Entity
@Table(name = "medecin", catalog = "prestation")
public class Medecin implements java.io.Serializable {

	private Integer id;
	private String nom;
	private Integer tauxJournalier;
	private String numero;
	private Set<Ordonnance> ordonnances = new HashSet<Ordonnance>(0);

	public Medecin() {
	}

	public Medecin(String nom, Integer tauxJournalier, String numero, Set<Ordonnance> ordonnances) {
		this.nom = nom;
		this.tauxJournalier = tauxJournalier;
		this.numero = numero;
		this.ordonnances = ordonnances;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nom")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "taux_journalier")
	public Integer getTauxJournalier() {
		return this.tauxJournalier;
	}

	public void setTauxJournalier(Integer tauxJournalier) {
		this.tauxJournalier = tauxJournalier;
	}

	@Column(name = "numero")
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medecin")
	public Set<Ordonnance> getOrdonnances() {
		return this.ordonnances;
	}

	public void setOrdonnances(Set<Ordonnance> ordonnances) {
		this.ordonnances = ordonnances;
	}

}
